[package]
name = "blendit"
version = "0.1.0"
authors = ["alexvilanovab <alexvilanovab@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
image = "0.23.14"
imageproc = "0.22.0"
indicatif = "0.15.0"
rusttype = "0.9.2"
